### PR TITLE
release: 0.19.1

### LINKED ISSUE #1204: cargo dist fails to compile from source with rust 1.78.0
I get the following error when installing via `cargo install cargo-dist`

```{shell}
error[E0716]: temporary value dropped while borrowed
   --> /home/XXX/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-dist-0.19.0/src/init.rs:882:10
    |
873 |     let install_path = if install_path.is_none()
    |         ------------ borrow later stored here
...
882 |         &Some(InstallPathStrategy::default_list())
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
883 |     } else {
    |     - temporary value is freed at the end of this statement
    |
    = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `cargo-dist` (lib) due to 1 previous error
error: failed to compile `cargo-dist v0.19.0`, intermediate artifacts can be found at `/mnt/scratch1/XXX/cargo-installyt5WVA`.
```

is 1.78.0 a supported Rust version?

### PR DESCRIPTION
**Pull request by Gankra**
fixes #1204

### CODE REVIEW

File: CHANGELOG.md [hunk 1]
```diff
@@ -3,6 +3,11 @@
 Nothing Yet!
 
 
+# Version 0.19.1 (2024-07-12)
+
+This is a minor release that makes cargo-dist build with versions of rustc older than 1.79.0 (as of this writing, the latest release). The previous cargo-dist release accidentally relied on the rustc's [new temporary lifetime extension features](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#extending-automatic-temporary-lifetime-extension), making us suddenly require bleeding edge rustc for no good reason.
```
Comment (ashleygwilliams) [inline CHANGELOG.md:8]: word minor here might be confusing but otherwise lgtm

**Review by ashleygwilliams — APPROVED** [review]

**Comment by Gankra** [comment]
(for merge conflict reasons i opened two PRs using the same base branch but different merge-target branches, this is the "doomed" PR that had working CI but went to a dummy branch. the other PR will be merged)
